clean-pyc:
	#find . -name '*.pyc' -exec rm --force {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm --force {} +
	find . -name '*~' -exec rm --force  {} +

run:
	python run.py
